### ISSUE TITLE
ohmage 2.x: Image object does not implement equal() and hashCode()

### ISSUE THREAD

**Issue by stevenolen** [ohmage/server#830]
Image object does not implement equal() and hashCode(), which causes java.util.Collection's [removeAll](http://docs.oracle.com/javase/6/docs/api/java/util/Collection.html#removeAll(java.util.Collection)) to fail to remove any duplicate objects from the `images` collection used in the [AsyncImageProcessor](https://github.com/ohmage/server/blob/master/src/org/ohmage/cache/AsyncImageProcessor.java#L79).

**Comment by hongsudt** [comment]
Fixed in 2.17.
