### ISSUE TITLE
ohmage 3 install doc?

### ISSUE THREAD

**Issue by gr21783** [ohmage/server#845]
Where is the ohmage 3 server code and install documentation? I can only find the installation documentation for version 2.x. It Is from 2013.

**Comment by stevenolen** [comment]
Hi @gr21783! The ohmage 3.0 codebase is now considered discontinued/unfinished.  The ohmage 2.x series is the correct/latest ohmage code base, with the latest version, 2.17, having just been minted this week!

While the setup instructions for 2.x are more-or-less accurate, we've added and will continue to add new ways (such as the [docker](https://github.com/ohmage/docker) container) to get started with ohmage quickly/effectively. 

Thanks for checking out ohmage!
