### ISSUE TITLE
admin user can delete him/herself

### ISSUE THREAD

**Issue by stevenolen** [ohmage/server#861]
Perhaps not a bug, but thought it best to open an issue.

I could see this being particular bad in the case where there is only one admin user available, and that admin user deletes their own account.  This effectively ruins the management of the ohmage server save for direct database manipulation (since ohmage admin is not necessarily the db admin).

Perhaps a check could be done to see if there is another admin on the system?

**Comment by stevenolen** [comment]
It's probably best to catch this in the client.  `admins in ohmage = great power + great responsibility`, we shouldn't hinder that on the server side.

**Comment by hongsudt** [comment]
Maybe in the documentation somewhere, we can list a workaround of what need
to be done if you have no admin account left.
