### ISSUE TITLE
Error 500 when not logged in

### ISSUE THREAD

**Issue by jeroenooms** [ohmage/server#863]
There is a recent bug in Ohmage that results in a HTTP 500 error when calling the API while not logged in.

To reproduce: make sure you are not logged in and navigate to https://test.mobilizingcs.org/#campaign_mgmt/.

**Comment by hongsudt** [comment]
Why would you call the server when u r not logged in?

**Comment by jeroenooms** [comment]
Because you don't know you're not logged in, or the session timed out or whatever. The server should be responding with an ohmage error code "0200" when the session is no longer valid so that the client knows he has to redirect to the login page. This always worked until recently.

**Comment by jeroenooms** [comment]
The laud server does not have this problem so it must be introduced recently.

**Comment by hongsudt** [comment]
I know.. I checked this last night. I will look into this further today.

**Comment by hongsudt** [comment]
resolved with commit b4f4804

**Comment by jeroenooms** [comment]
Thanks for fixing
