### ISSUE TITLE
Class read does not raise error

### ISSUE THREAD

**Issue by jeroenooms** [ohmage/server#864]
The `/app/class/read` api returns success when you use a non-existing `urn`. Not sure if this is intended but it makes it impossible to see if a campaign really exists.

**Comment by hongsudt** [comment]
class read is acting like class search.. It queries the required entries based on the specified parameters. If none of the criteria is met, it returns a success status with an empty object. This seems to be the behavior of most of the read apis..

**Comment by stevenolen** [comment]
Since this is how many of the 2.x apis operate, it's best to leave as is for backwards compatibility. Closing.
