### ISSUE TITLE
add survey_response/function/read details to campaign/read(long)

### ISSUE THREAD

**Issue by stevenolen** [ohmage/server#880]
@hongsudt could you take a look and see if this would kill the server performance? It looks like one of the best ways to improve performance for @jeroenooms' campaign tool.

**Comment by jeroenooms** [comment]
Yes so most of the loading time is spent doing all of the `/function/read` requests to get the response counts for each campaign. If we can instead let the server do a single `select COUNT(*) from responses group by campaign` that would be much more efficient.

**Comment by stevenolen** [comment]
fixed in cc7e56dd8c0957fd56e8d54e84ce480328ad1d91
