### ISSUE TITLE
api docs and latest version

### ISSUE THREAD

**Issue by satra** [ohmage/server#891]
we are building an app to interface with ohmage 2.x but would like to work with the latest release of the server. is this the best version and if so is there a location for api docs for this server?

**Comment by stevenolen** [comment]
Hi @satra! Yes, and we've actually just released a new version yesterday: https://github.com/ohmage/server/releases/tag/v2.18.0

The API docs are in the wiki, but here's a direct link to the top-level of the api docs you're likely to want to look at: https://github.com/ohmage/server/wiki/APIs-for-2.x-Top-Level-Entities

Finally, if you're looking to build an app using javascript, take a look at our javascript library: https://github.com/ohmage/ohmage.js or the navbar project, which offers a frontend microservice-like architecture for making small and efficient frontends for ohmage (you can see most of the other frontend projects in the mobilizingcs org as well): https://github.com/mobilizingcs/navbar

Additionally, collaborators at UCLA have a phonegap app that may do much of what you are looking for: https://github.com/ucla/ohmageX

Thanks for using ohmage!
