### ISSUE TITLE
Document default admin password

### ISSUE THREAD

**Issue by krozett** [ohmage/server#893]
On a fresh install, the database is seeded with a user called ohmage.admin, and a certain password. (I'm not going to post it here in case it's meant to be secret.)

If you look at the `/db/sql/settings/default_admin.sql` file, it inserts a hashed password which is of no use to anyone trying to log in to their new install. We need to either document this default password somewhere or alter the seed data so that people who look at the code can see the bare password. Not sure if there is an SQL function for this, like `MD5('therealpassword')` rather than the hashed string.

**Comment by stevenolen** [comment]
hi @krozett! a few things:

  * The default password is OK to put in public (`ohmage.passwd`) and I've made sure to reference it better in the README: https://github.com/ohmage/server/commit/fb1bb257be33d3ce0f3301039d126038067587dc
  * The `db/sql` references are EOL as of ohmage 2.17, so it is best to execute migrations and seeding using flyway, just to be clear!

I think that should clear it up, sorry for the confusion!
