### ISSUE TITLE
migrations will fail on mysql 5.7.15 ubuntu 16.04

### ISSUE THREAD

**Issue by dPeS** [ohmage/server#897]
with:
Incorrect datetime value: '0' for column 'last_modified_timestamp' at row 1
on:
UPDATE class SET last_modified_timestamp = 0

since mysql switched to strict SQL mode on this:

https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_sql_mode

the workaround is to add:

sql_mode        = ''
in [mysqld] section of /etc/mysql/mysql.conf.d/mysqld.cnf file + mysqld restart

regards,

**Comment by stevenolen** [comment]
thank you for reporting! in our README we currently mention to use mysql 5.5 (although mysql 5.6 is also compatible). MySQL 5.7 has some changes that may cause some issues (one of those you're seeing above!)

MySQL 5.7 support is not currently slated.
